CREATE DATABASE Restaurant;

USE Restaurant;

CREATE TABLE Restaurants (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(50) NOT NULL,
	Address VARCHAR(50) NOT NULL,
	PhoneNumber VARCHAR(50) NOT NULL,
	OpeningHours VARCHAR(50) NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	UpdatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	CreatedBy INT,
	UpdatedBy INT
);

CREATE TABLE Employees (
	Id INT PRIMARY KEY IDENTITY(1,1),
	RestaurantId INT NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	Position VARCHAR(50) NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	UpdatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	CreatedBy INT,
	UpdatedBy INT,
	FOREIGN KEY (RestaurantId) REFERENCES Restaurants(Id)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE Customers (
	Id INT PRIMARY KEY IDENTITY(1,1),
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	PhoneNumber VARCHAR(50) NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	UpdatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	CreatedBy INT,
	UpdatedBy INT
);

CREATE TABLE MenuItems (
	Id INT PRIMARY KEY IDENTITY(1,1),
	RestaurantId INT NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Description VARCHAR(50) NOT NULL,
	Price DECIMAL(10,2) NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	UpdatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	CreatedBy INT,
	UpdatedBy INT,
	FOREIGN KEY (RestaurantId) REFERENCES Restaurants(Id)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE Reservations (
	Id INT PRIMARY KEY IDENTITY(1,1),
	RestaurantId INT NOT NULL,
	CustomerId INT NOT NULL,
	PartySize INT NOT NULL,
	Status VARCHAR(50) NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	UpdatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	CreatedBy INT,
	UpdatedBy INT,
	FOREIGN KEY (RestaurantId) REFERENCES Restaurants(Id)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	FOREIGN KEY (CustomerId) REFERENCES Customers(Id)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE Tables (
	Id INT PRIMARY KEY IDENTITY(1,1),
	RestaurantId INT NOT NULL,
	TableNumber INT NOT NULL,
	Capacity INT NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	UpdatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	CreatedBy INT,
	UpdatedBy INT,
	FOREIGN KEY (RestaurantId) REFERENCES Restaurants(Id)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	UNIQUE (RestaurantId, TableNumber)
);

CREATE TABLE ReservationTable (
	TableId INT NOT NULL,
	ReservationId INT NOT NULL,
	AssignedSeats INT NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	UpdatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	CreatedBy INT,
	UpdatedBy INT,
	PRIMARY KEY (TableId, ReservationId),
	FOREIGN KEY (TableId) REFERENCES Tables(Id),
	FOREIGN KEY (ReservationId) REFERENCES Reservations(Id)
);

CREATE TABLE Orders (
	Id INT PRIMARY KEY IDENTITY(1,1),
	ReservationId INT NOT NULL,
	EmployeeId INT NOT NULL,
	TotalPrice DECIMAL(10,2) NOT NULL,
	Discount DECIMAL(10,2),
	Tax DECIMAL(10,2),
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	UpdatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	CreatedBy INT,
	UpdatedBy INT,
	FOREIGN KEY (ReservationId) REFERENCES Reservations(Id),
	FOREIGN KEY (EmployeeId) REFERENCES Employees(Id)
);



CREATE TABLE OrderItems (
	Id INT PRIMARY KEY IDENTITY(1,1),
	OrderId INT NOT NULL,
	MenuItemId INT NOT NULL,
	Quantity INT NOT NULL,
	Notes VARCHAR(100),
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	UpdatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	CreatedBy INT,
	UpdatedBy INT,
	FOREIGN KEY (OrderId) REFERENCES Orders(Id)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	FOREIGN KEY (MenuItemId) REFERENCES MenuItems(Id)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);